name: Trigger Jenkins

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: curl http://<EC2-IP>:8080/job/static-site/build
